$axure.loadCurrentPage({
  "url":"home.html",
  "generationDate":new Date(1405186598138.91),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"6a8deb958aed482aaefbec8bcb0d2ef1",
    "type":"Axure:Page",
    "name":"Home",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"96d3137edcbc465ebf55d2941387ce82",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":480,
              "height":800}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35999084aadc4afda305a9eea1e1c0a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":480,
                  "height":800}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"7f6c095c54e34642bbe9a66867786438",
          "label":"home",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":480,
              "height":800}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"1f71b1e744354bab8ca7566203adda43",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"ee0d09228e8b45939150acafaf2ee8cf",
                  "label":"input",
                  "parentDynamicPanel":"7f6c095c54e34642bbe9a66867786438",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":90,
                      "y":20},
                    "size":{
                      "width":300,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onTextChange":{
                      "description":"OnTextChange",
                      "cases":[{
                          "description":"Case 1<br> (If text on This does not equal &quot;&quot;)",
                          "isNewIfGroup":false,
                          "condition":{
                            "exprType":"binaryOp",
                            "op":"!=",
                            "leftExpr":{
                              "exprType":"fcall",
                              "functionName":"GetWidgetText",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":true,
                                  "isFocused":false,
                                  "isTarget":false}]},
                            "rightExpr":{
                              "exprType":"stringLiteral",
                              "value":"",
                              "stos":[]}},
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"Show 输入法 slide up 100 ms",
                              "objectsToFades":[{
                                  "objectPath":["ab1b287d5c2d4ecfa34baa6650edf617"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "easing":"slideUp",
                                      "duration":100,
                                      "showType":"none"}}}]},
{
                              "action":"fadeWidget",
                              "description":"Show 下拉",
                              "objectsToFades":[{
                                  "objectPath":["15abf91ef0f343a183314648490b6763"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]},
{
                          "description":"Case 2<br> (Else If text on This equals &quot;&quot;)",
                          "isNewIfGroup":false,
                          "condition":{
                            "exprType":"binaryOp",
                            "op":"==",
                            "leftExpr":{
                              "exprType":"fcall",
                              "functionName":"GetWidgetText",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":true,
                                  "isFocused":false,
                                  "isTarget":false}]},
                            "rightExpr":{
                              "exprType":"stringLiteral",
                              "value":"",
                              "stos":[]}},
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"Hide 下拉",
                              "objectsToFades":[{
                                  "objectPath":["15abf91ef0f343a183314648490b6763"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}}},
{
                  "id":"c4823b298a7a4cd9a6c6fed996f6bed9",
                  "label":"searchbg",
                  "parentDynamicPanel":"7f6c095c54e34642bbe9a66867786438",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":380,
                      "y":375},
                    "size":{
                      "width":50,
                      "height":30},
                    "borderWidth":"2",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6c840b2d0e4c483c8375c9fa378f018f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7f6c095c54e34642bbe9a66867786438",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":380,
                          "y":375},
                        "size":{
                          "width":50,
                          "height":30},
                        "borderWidth":"2",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/searchbg_u4.png"}},
{
                  "id":"e1bc2e7bef8042f4ac7a58a15f5a07ff",
                  "label":"search",
                  "parentDynamicPanel":"7f6c095c54e34642bbe9a66867786438",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":395,
                      "y":380},
                    "size":{
                      "width":20,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b65456360d7448b480aae17d53b020a4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7f6c095c54e34642bbe9a66867786438",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":395,
                          "y":380},
                        "size":{
                          "width":20,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Page 1 in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"page_1.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/search_u6.png"}},
{
                  "id":"8d9680b53f0b4991811365b4a6bbfa0a",
                  "label":"",
                  "parentDynamicPanel":"7f6c095c54e34642bbe9a66867786438",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":375},
                    "size":{
                      "width":330,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onFocus":{
                      "description":"OnFocus",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"Hide This",
                              "objectsToFades":[{
                                  "objectPath":["8d9680b53f0b4991811365b4a6bbfa0a"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"moveWidget",
                              "description":"Move line by (40,0) linear 500ms,<br>searchbg by (30,0) linear 500ms,<br>search by (30,0) linear 500ms",
                              "objectsToMoves":[{
                                  "objectPath":["abb4c02e76d44dcdaf0e6ec2867f88a3"],
                                  "moveInfo":{
                                    "moveType":"delta",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"40",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "options":{
                                      "easing":"linear",
                                      "duration":500}}},
{
                                  "objectPath":["c4823b298a7a4cd9a6c6fed996f6bed9"],
                                  "moveInfo":{
                                    "moveType":"delta",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"30",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "options":{
                                      "easing":"linear",
                                      "duration":500}}},
{
                                  "objectPath":["e1bc2e7bef8042f4ac7a58a15f5a07ff"],
                                  "moveInfo":{
                                    "moveType":"delta",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"30",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "options":{
                                      "easing":"linear",
                                      "duration":500}}}]},
{
                              "action":"moveWidget",
                              "description":"Move line to (90,45) linear 500ms",
                              "objectsToMoves":[{
                                  "objectPath":["abb4c02e76d44dcdaf0e6ec2867f88a3"],
                                  "moveInfo":{
                                    "moveType":"location",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"90",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"45",
                                      "stos":[]},
                                    "options":{
                                      "easing":"linear",
                                      "duration":500}}}]},
{
                              "action":"moveWidget",
                              "description":"Move search to (425,25) linear 500ms,<br>searchbg to (410,20) linear 500ms",
                              "objectsToMoves":[{
                                  "objectPath":["e1bc2e7bef8042f4ac7a58a15f5a07ff"],
                                  "moveInfo":{
                                    "moveType":"location",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"425",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"25",
                                      "stos":[]},
                                    "options":{
                                      "easing":"linear",
                                      "duration":500}}},
{
                                  "objectPath":["c4823b298a7a4cd9a6c6fed996f6bed9"],
                                  "moveInfo":{
                                    "moveType":"location",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"410",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"20",
                                      "stos":[]},
                                    "options":{
                                      "easing":"linear",
                                      "duration":500}}}]},
{
                              "action":"fadeWidget",
                              "description":"Hide 1 slide left 1000 ms",
                              "objectsToFades":[{
                                  "objectPath":["a30f001697ab4f7b8675908d927282a3"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "easing":"slideLeft",
                                      "duration":1000,
                                      "showType":"none"}}}]},
{
                              "action":"setFocusOnWidget",
                              "description":"Set Focus on input",
                              "objectPaths":[["ee0d09228e8b45939150acafaf2ee8cf"]]}]}]}},
                  "tabbable":true},
{
                  "id":"abb4c02e76d44dcdaf0e6ec2867f88a3",
                  "label":"line",
                  "parentDynamicPanel":"7f6c095c54e34642bbe9a66867786438",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":50,
                      "y":400},
                    "size":{
                      "width":300,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/home/line_u9_line.png"}},
{
                  "id":"5dd95031389c4317aa8fe629436a836d",
                  "label":"",
                  "parentDynamicPanel":"7f6c095c54e34642bbe9a66867786438",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":20},
                    "size":{
                      "width":50,
                      "height":30},
                    "borderWidth":"2",
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"75ffd13b65eb4da08e2c546da7a2c26a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7f6c095c54e34642bbe9a66867786438",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":20},
                        "size":{
                          "width":50,
                          "height":30},
                        "borderWidth":"2",
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u10.png"}},
{
                  "id":"10701be4a48a4428a183b0bb0fd0c501",
                  "label":"",
                  "parentDynamicPanel":"7f6c095c54e34642bbe9a66867786438",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":20},
                    "size":{
                      "width":50,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"188f2eecebc747498003108fd934222f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7f6c095c54e34642bbe9a66867786438",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":20},
                        "size":{
                          "width":50,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u12.png"}},
{
                  "id":"a30f001697ab4f7b8675908d927282a3",
                  "label":"1",
                  "parentDynamicPanel":"7f6c095c54e34642bbe9a66867786438",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"14px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "size":{
                      "width":480,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a489813cf87342d0bd08d86b962055fa",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7f6c095c54e34642bbe9a66867786438",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontSize":"14px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "size":{
                          "width":480,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/1_u14.png"}},
{
                  "id":"15abf91ef0f343a183314648490b6763",
                  "label":"下拉",
                  "parentDynamicPanel":"7f6c095c54e34642bbe9a66867786438",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":false,
                  "style":{
                    "location":{
                      "x":90,
                      "y":50},
                    "size":{
                      "width":300,
                      "height":440},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Page 1 in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"page_1.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "scrollbars":"none",
                  "fitToContent":false,
                  "propagate":false,
                  "diagrams":[{
                      "id":"a9d06e291b7341e7a8a793f41542cc81",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"72638d093f744e659ad126a7ef7fefe0",
                          "label":"",
                          "parentDynamicPanel":"15abf91ef0f343a183314648490b6763",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":300,
                              "height":440}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"7cd39aef8d9c419a96bd25f1afb76f5e",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"15abf91ef0f343a183314648490b6763",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "size":{
                                  "width":300,
                                  "height":440}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/home/u17.png"}},
{
                          "id":"89e8d82e906a4b4eb9ce561ae0acc777",
                          "label":"",
                          "parentDynamicPanel":"15abf91ef0f343a183314648490b6763",
                          "type":"horizontalLine",
                          "styleType":"horizontalLine",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":0,
                              "y":50},
                            "size":{
                              "width":300,
                              "height":10}},
                          "adaptiveStyles":{
},
                          "images":{
                            "start~":"resources/images/transparent.gif",
                            "end~":"resources/images/transparent.gif",
                            "line~":"images/home/line_u9_line.png"}},
{
                          "id":"53200b1af458402eadd0b2325134cb3d",
                          "label":"",
                          "parentDynamicPanel":"15abf91ef0f343a183314648490b6763",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "location":{
                              "x":10,
                              "y":0},
                            "size":{
                              "width":280,
                              "height":56}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"23af9d0d70bc471ea2c7b28386a77c9f",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"15abf91ef0f343a183314648490b6763",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "verticalAlignment":"middle",
                                "location":{
                                  "x":10,
                                  "y":0},
                                "size":{
                                  "width":280,
                                  "height":56}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"88d8b0a375bc4fef875458ce50034655",
                          "label":"",
                          "parentDynamicPanel":"15abf91ef0f343a183314648490b6763",
                          "type":"horizontalLine",
                          "styleType":"horizontalLine",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":0,
                              "y":100},
                            "size":{
                              "width":300,
                              "height":10}},
                          "adaptiveStyles":{
},
                          "images":{
                            "start~":"resources/images/transparent.gif",
                            "end~":"resources/images/transparent.gif",
                            "line~":"images/home/line_u9_line.png"}},
{
                          "id":"fb939812107b4387bf2d3412572299ca",
                          "label":"",
                          "parentDynamicPanel":"15abf91ef0f343a183314648490b6763",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "location":{
                              "x":10,
                              "y":50},
                            "size":{
                              "width":280,
                              "height":56}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"eaab26ffbb5f4dd7956849cd16432bd8",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"15abf91ef0f343a183314648490b6763",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "verticalAlignment":"middle",
                                "location":{
                                  "x":10,
                                  "y":50},
                                "size":{
                                  "width":280,
                                  "height":56}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"1b1a639dbbe247a19f1f572631aa301a",
                          "label":"",
                          "parentDynamicPanel":"15abf91ef0f343a183314648490b6763",
                          "type":"horizontalLine",
                          "styleType":"horizontalLine",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":0,
                              "y":150},
                            "size":{
                              "width":300,
                              "height":10}},
                          "adaptiveStyles":{
},
                          "images":{
                            "start~":"resources/images/transparent.gif",
                            "end~":"resources/images/transparent.gif",
                            "line~":"images/home/line_u9_line.png"}},
{
                          "id":"21c2ab6b70b4433aa582b6f8c9ff2fcc",
                          "label":"",
                          "parentDynamicPanel":"15abf91ef0f343a183314648490b6763",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "location":{
                              "x":10,
                              "y":100},
                            "size":{
                              "width":280,
                              "height":56}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"5e9c2f311a5849eb9d012cc1a5b42834",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"15abf91ef0f343a183314648490b6763",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "verticalAlignment":"middle",
                                "location":{
                                  "x":10,
                                  "y":100},
                                "size":{
                                  "width":280,
                                  "height":56}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"273afe8632494c93b714e426228b359f",
                          "label":"",
                          "parentDynamicPanel":"15abf91ef0f343a183314648490b6763",
                          "type":"horizontalLine",
                          "styleType":"horizontalLine",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":0,
                              "y":200},
                            "size":{
                              "width":300,
                              "height":10}},
                          "adaptiveStyles":{
},
                          "images":{
                            "start~":"resources/images/transparent.gif",
                            "end~":"resources/images/transparent.gif",
                            "line~":"images/home/line_u9_line.png"}},
{
                          "id":"e6d9ebced7d3444cbaab8e4477467436",
                          "label":"",
                          "parentDynamicPanel":"15abf91ef0f343a183314648490b6763",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "location":{
                              "x":10,
                              "y":150},
                            "size":{
                              "width":280,
                              "height":56}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"1634345ccf4544029c173cc672641a2d",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"15abf91ef0f343a183314648490b6763",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "verticalAlignment":"middle",
                                "location":{
                                  "x":10,
                                  "y":150},
                                "size":{
                                  "width":280,
                                  "height":56}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"d82c89a392ae456cac10c3ba37047309",
                          "label":"",
                          "parentDynamicPanel":"15abf91ef0f343a183314648490b6763",
                          "type":"horizontalLine",
                          "styleType":"horizontalLine",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":0,
                              "y":250},
                            "size":{
                              "width":300,
                              "height":10}},
                          "adaptiveStyles":{
},
                          "images":{
                            "start~":"resources/images/transparent.gif",
                            "end~":"resources/images/transparent.gif",
                            "line~":"images/home/line_u9_line.png"}},
{
                          "id":"8b0e29397eea417f97ee9982c11d0b02",
                          "label":"",
                          "parentDynamicPanel":"15abf91ef0f343a183314648490b6763",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "location":{
                              "x":10,
                              "y":200},
                            "size":{
                              "width":280,
                              "height":56}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"9ff2e4ae5d7c4284bfce554c0277c027",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"15abf91ef0f343a183314648490b6763",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "verticalAlignment":"middle",
                                "location":{
                                  "x":10,
                                  "y":200},
                                "size":{
                                  "width":280,
                                  "height":56}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"d327001c20554d9ca48e1cf9300cf798",
                          "label":"",
                          "parentDynamicPanel":"15abf91ef0f343a183314648490b6763",
                          "type":"horizontalLine",
                          "styleType":"horizontalLine",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":0,
                              "y":300},
                            "size":{
                              "width":300,
                              "height":10}},
                          "adaptiveStyles":{
},
                          "images":{
                            "start~":"resources/images/transparent.gif",
                            "end~":"resources/images/transparent.gif",
                            "line~":"images/home/line_u9_line.png"}},
{
                          "id":"0d4aad0b62324082aa5043c5e6e7f7a9",
                          "label":"",
                          "parentDynamicPanel":"15abf91ef0f343a183314648490b6763",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "location":{
                              "x":10,
                              "y":250},
                            "size":{
                              "width":280,
                              "height":56}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"cc21965666b047e1aff03b537bc49454",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"15abf91ef0f343a183314648490b6763",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "verticalAlignment":"middle",
                                "location":{
                                  "x":10,
                                  "y":250},
                                "size":{
                                  "width":280,
                                  "height":56}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"b5de145b695a489b93b77a442d47955c",
                          "label":"",
                          "parentDynamicPanel":"15abf91ef0f343a183314648490b6763",
                          "type":"horizontalLine",
                          "styleType":"horizontalLine",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":0,
                              "y":400},
                            "size":{
                              "width":300,
                              "height":10}},
                          "adaptiveStyles":{
},
                          "images":{
                            "start~":"resources/images/transparent.gif",
                            "end~":"resources/images/transparent.gif",
                            "line~":"images/home/line_u9_line.png"}},
{
                          "id":"faf6170de7104571a87f56761cd44371",
                          "label":"",
                          "parentDynamicPanel":"15abf91ef0f343a183314648490b6763",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "location":{
                              "x":10,
                              "y":350},
                            "size":{
                              "width":280,
                              "height":56}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"1e42728e26cc42238bdea5bf71603bab",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"15abf91ef0f343a183314648490b6763",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "verticalAlignment":"middle",
                                "location":{
                                  "x":10,
                                  "y":350},
                                "size":{
                                  "width":280,
                                  "height":56}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"ec7a73cef5464ebc8a5d8f0a7dbb7193",
                          "label":"",
                          "parentDynamicPanel":"15abf91ef0f343a183314648490b6763",
                          "type":"horizontalLine",
                          "styleType":"horizontalLine",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":0,
                              "y":350},
                            "size":{
                              "width":300,
                              "height":10}},
                          "adaptiveStyles":{
},
                          "images":{
                            "start~":"resources/images/transparent.gif",
                            "end~":"resources/images/transparent.gif",
                            "line~":"images/home/line_u9_line.png"}},
{
                          "id":"3aea687b419946958fd479efbeea0728",
                          "label":"",
                          "parentDynamicPanel":"15abf91ef0f343a183314648490b6763",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "location":{
                              "x":10,
                              "y":300},
                            "size":{
                              "width":280,
                              "height":56}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"2d5903091bf44db39e74b4ed277dc156",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"15abf91ef0f343a183314648490b6763",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "verticalAlignment":"middle",
                                "location":{
                                  "x":10,
                                  "y":300},
                                "size":{
                                  "width":280,
                                  "height":56}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"207adf75f44e4fefa30b6a02739d915c",
                          "label":"",
                          "parentDynamicPanel":"15abf91ef0f343a183314648490b6763",
                          "type":"horizontalLine",
                          "styleType":"horizontalLine",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":0,
                              "y":450},
                            "size":{
                              "width":300,
                              "height":10}},
                          "adaptiveStyles":{
},
                          "images":{
                            "start~":"resources/images/transparent.gif",
                            "end~":"resources/images/transparent.gif",
                            "line~":"images/home/line_u9_line.png"}},
{
                          "id":"cd86eeac5f2a41dba452fe0687bd244c",
                          "label":"",
                          "parentDynamicPanel":"15abf91ef0f343a183314648490b6763",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "location":{
                              "x":10,
                              "y":400},
                            "size":{
                              "width":280,
                              "height":56}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"312ae6560dca4f3b9b73b5d2154bc255",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"15abf91ef0f343a183314648490b6763",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "verticalAlignment":"middle",
                                "location":{
                                  "x":10,
                                  "y":400},
                                "size":{
                                  "width":280,
                                  "height":56}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}}]}]},
{
                  "id":"ab1b287d5c2d4ecfa34baa6650edf617",
                  "label":"输入法",
                  "parentDynamicPanel":"7f6c095c54e34642bbe9a66867786438",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":false,
                  "style":{
                    "location":{
                      "x":0,
                      "y":470},
                    "size":{
                      "width":480,
                      "height":330},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":false,
                  "propagate":false,
                  "diagrams":[{
                      "id":"a2a7ebdb69854c92ab6ec353f6ef968b",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"402124622abc41d0a76b02cd42e5d72b",
                          "label":"",
                          "parentDynamicPanel":"ab1b287d5c2d4ecfa34baa6650edf617",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":480,
                              "height":331}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"dead8cbf02844ba48bf0be59b36d9ad8",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"ab1b287d5c2d4ecfa34baa6650edf617",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "size":{
                                  "width":480,
                                  "height":331}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/home/u47.png"}}]}]}]},
{
              "id":"eb4da4c6e9564cadbf9652e60414ac11",
              "label":"State2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"7ae80747e615484595404e7ebd11bcd4",
                  "label":"",
                  "parentDynamicPanel":"7f6c095c54e34642bbe9a66867786438",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":90,
                      "y":40},
                    "size":{
                      "width":300,
                      "height":10},
                    "borderWidth":"2"},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/home/u49_line.png"}},
{
                  "id":"04f7f0b83fe84f4581dc43acf0c42388",
                  "label":"",
                  "parentDynamicPanel":"7f6c095c54e34642bbe9a66867786438",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":410,
                      "y":20},
                    "size":{
                      "width":50,
                      "height":30},
                    "borderWidth":"2",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ffc7438786384a9086f0e8e5f3d490b4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7f6c095c54e34642bbe9a66867786438",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":410,
                          "y":20},
                        "size":{
                          "width":50,
                          "height":30},
                        "borderWidth":"2",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/searchbg_u4.png"}},
{
                  "id":"58c10943371a44f19da3ac6e0587e4f2",
                  "label":"",
                  "parentDynamicPanel":"7f6c095c54e34642bbe9a66867786438",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":426,
                      "y":26},
                    "size":{
                      "width":19,
                      "height":18}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b55d732101f24c31b8b26022a7e77ac6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7f6c095c54e34642bbe9a66867786438",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":426,
                          "y":26},
                        "size":{
                          "width":19,
                          "height":18}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/search_u6.png"}},
{
                  "id":"36036baad6ba4cbf88fab56ffec9d510",
                  "label":"",
                  "parentDynamicPanel":"7f6c095c54e34642bbe9a66867786438",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":20},
                    "size":{
                      "width":50,
                      "height":30},
                    "borderWidth":"2",
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"666281e5c61b4d5788cb8f0671e1c352",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7f6c095c54e34642bbe9a66867786438",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":20},
                        "size":{
                          "width":50,
                          "height":30},
                        "borderWidth":"2",
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u10.png"}},
{
                  "id":"33c3d801037d49ffa2747c647013d1b9",
                  "label":"",
                  "parentDynamicPanel":"7f6c095c54e34642bbe9a66867786438",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":20},
                    "size":{
                      "width":50,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2f3fd93d7ccc4655908248ba6300fa78",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7f6c095c54e34642bbe9a66867786438",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":20},
                        "size":{
                          "width":50,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u12.png"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "96d3137edcbc465ebf55d2941387ce82":{
      "scriptId":"u0"},
    "35999084aadc4afda305a9eea1e1c0a4":{
      "scriptId":"u1"},
    "7f6c095c54e34642bbe9a66867786438":{
      "scriptId":"u2"},
    "ee0d09228e8b45939150acafaf2ee8cf":{
      "scriptId":"u3"},
    "c4823b298a7a4cd9a6c6fed996f6bed9":{
      "scriptId":"u4"},
    "6c840b2d0e4c483c8375c9fa378f018f":{
      "scriptId":"u5"},
    "e1bc2e7bef8042f4ac7a58a15f5a07ff":{
      "scriptId":"u6"},
    "b65456360d7448b480aae17d53b020a4":{
      "scriptId":"u7"},
    "8d9680b53f0b4991811365b4a6bbfa0a":{
      "scriptId":"u8"},
    "abb4c02e76d44dcdaf0e6ec2867f88a3":{
      "scriptId":"u9"},
    "5dd95031389c4317aa8fe629436a836d":{
      "scriptId":"u10"},
    "75ffd13b65eb4da08e2c546da7a2c26a":{
      "scriptId":"u11"},
    "10701be4a48a4428a183b0bb0fd0c501":{
      "scriptId":"u12"},
    "188f2eecebc747498003108fd934222f":{
      "scriptId":"u13"},
    "a30f001697ab4f7b8675908d927282a3":{
      "scriptId":"u14"},
    "a489813cf87342d0bd08d86b962055fa":{
      "scriptId":"u15"},
    "15abf91ef0f343a183314648490b6763":{
      "scriptId":"u16"},
    "72638d093f744e659ad126a7ef7fefe0":{
      "scriptId":"u17"},
    "7cd39aef8d9c419a96bd25f1afb76f5e":{
      "scriptId":"u18"},
    "89e8d82e906a4b4eb9ce561ae0acc777":{
      "scriptId":"u19"},
    "53200b1af458402eadd0b2325134cb3d":{
      "scriptId":"u20"},
    "23af9d0d70bc471ea2c7b28386a77c9f":{
      "scriptId":"u21"},
    "88d8b0a375bc4fef875458ce50034655":{
      "scriptId":"u22"},
    "fb939812107b4387bf2d3412572299ca":{
      "scriptId":"u23"},
    "eaab26ffbb5f4dd7956849cd16432bd8":{
      "scriptId":"u24"},
    "1b1a639dbbe247a19f1f572631aa301a":{
      "scriptId":"u25"},
    "21c2ab6b70b4433aa582b6f8c9ff2fcc":{
      "scriptId":"u26"},
    "5e9c2f311a5849eb9d012cc1a5b42834":{
      "scriptId":"u27"},
    "273afe8632494c93b714e426228b359f":{
      "scriptId":"u28"},
    "e6d9ebced7d3444cbaab8e4477467436":{
      "scriptId":"u29"},
    "1634345ccf4544029c173cc672641a2d":{
      "scriptId":"u30"},
    "d82c89a392ae456cac10c3ba37047309":{
      "scriptId":"u31"},
    "8b0e29397eea417f97ee9982c11d0b02":{
      "scriptId":"u32"},
    "9ff2e4ae5d7c4284bfce554c0277c027":{
      "scriptId":"u33"},
    "d327001c20554d9ca48e1cf9300cf798":{
      "scriptId":"u34"},
    "0d4aad0b62324082aa5043c5e6e7f7a9":{
      "scriptId":"u35"},
    "cc21965666b047e1aff03b537bc49454":{
      "scriptId":"u36"},
    "b5de145b695a489b93b77a442d47955c":{
      "scriptId":"u37"},
    "faf6170de7104571a87f56761cd44371":{
      "scriptId":"u38"},
    "1e42728e26cc42238bdea5bf71603bab":{
      "scriptId":"u39"},
    "ec7a73cef5464ebc8a5d8f0a7dbb7193":{
      "scriptId":"u40"},
    "3aea687b419946958fd479efbeea0728":{
      "scriptId":"u41"},
    "2d5903091bf44db39e74b4ed277dc156":{
      "scriptId":"u42"},
    "207adf75f44e4fefa30b6a02739d915c":{
      "scriptId":"u43"},
    "cd86eeac5f2a41dba452fe0687bd244c":{
      "scriptId":"u44"},
    "312ae6560dca4f3b9b73b5d2154bc255":{
      "scriptId":"u45"},
    "ab1b287d5c2d4ecfa34baa6650edf617":{
      "scriptId":"u46"},
    "402124622abc41d0a76b02cd42e5d72b":{
      "scriptId":"u47"},
    "dead8cbf02844ba48bf0be59b36d9ad8":{
      "scriptId":"u48"},
    "7ae80747e615484595404e7ebd11bcd4":{
      "scriptId":"u49"},
    "04f7f0b83fe84f4581dc43acf0c42388":{
      "scriptId":"u50"},
    "ffc7438786384a9086f0e8e5f3d490b4":{
      "scriptId":"u51"},
    "58c10943371a44f19da3ac6e0587e4f2":{
      "scriptId":"u52"},
    "b55d732101f24c31b8b26022a7e77ac6":{
      "scriptId":"u53"},
    "36036baad6ba4cbf88fab56ffec9d510":{
      "scriptId":"u54"},
    "666281e5c61b4d5788cb8f0671e1c352":{
      "scriptId":"u55"},
    "33c3d801037d49ffa2747c647013d1b9":{
      "scriptId":"u56"},
    "2f3fd93d7ccc4655908248ba6300fa78":{
      "scriptId":"u57"}}});