$axure.loadCurrentPage({
  "url":"page_1.html",
  "generationDate":new Date(1405186598362.93),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8ca77f966e9a42b8867b06a50b5b86e5",
    "type":"Axure:Page",
    "name":"Page 1",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d993d1e82c1c4714af9f435e79563a5b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":480,
              "height":800}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e019c9a074b485b8843927a787cc443",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":480,
                  "height":800}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"03a356bbeb51488eb75550cd59384864",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":50,
              "height":30},
            "borderWidth":"2",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8483295623cd489cbc8b8bf410f6dfcb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":50,
                  "height":30},
                "borderWidth":"2",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u10.png"}},
{
          "id":"7842372ac2564f7a849166f241575f94",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":90,
              "y":22},
            "size":{
              "width":370,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"adbb2432308b4417b77796b18f3e0f99",
          "label":"line",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":89.9999847412109,
              "y":40},
            "size":{
              "width":370,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/page_1/line_u5_line.png"}},
{
          "id":"1c6e5120861b474f89a1b6cc514ff081",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":50,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63e96e3fa5774110a91c24bd3248f842",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":50,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u12.png"}},
{
          "id":"13d728f363f64bab98c01a72e92fa7a9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":430,
              "y":20},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb0f0429d4a341f8ba97e3af4a3210f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":430,
                  "y":20},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set text on (Text Field) equal to &quot;&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetFormText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["7842372ac2564f7a849166f241575f94"]},
{
                                "exprType":"stringLiteral",
                                "value":"",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/page_1/u8.png"}},
{
          "id":"8f5a3886bdeb49a680caf66eec16dfb1",
          "label":"map",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":550},
            "size":{
              "width":440,
              "height":230},
            "borderWidth":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14f0d2d4cf7d492c90187a4a0e0a31d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":550},
                "size":{
                  "width":440,
                  "height":230},
                "borderWidth":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/map_u10.png"}},
{
          "id":"47cd58fcc61e40a199a0dc6056681dac",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":20,
              "y":70},
            "size":{
              "width":440,
              "height":150},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5374e0ea6444d26941c376235189c80",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":20,
                  "y":70},
                "size":{
                  "width":440,
                  "height":150},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u12.png"}},
{
          "id":"ffc06f03ee6c412682faeaba0c324d0d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'幼圆 Bold', '幼圆'",
            "location":{
              "x":36,
              "y":85},
            "size":{
              "width":325,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"932df56f7f134a4ea2218a0ac726a0c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'幼圆 Bold', '幼圆'",
                "location":{
                  "x":36,
                  "y":85},
                "size":{
                  "width":325,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Hide map fade 500 ms",
                      "objectsToFades":[{
                          "objectPath":["8f5a3886bdeb49a680caf66eec16dfb1"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "easing":"fade",
                              "duration":500,
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"Show map fade 500 ms",
                      "objectsToFades":[{
                          "objectPath":["8f5a3886bdeb49a680caf66eec16dfb1"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"fade",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"66a482416abf4a2ea101d195155d8cac",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":376,
              "y":70},
            "size":{
              "width":84,
              "height":150},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"802ff3c182d043a983b33d42a51fea07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":376,
                  "y":70},
                "size":{
                  "width":84,
                  "height":150},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Page 2 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"page_2.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/page_1/u16.png"}},
{
          "id":"33c16d887839452f821763f5a8b18203",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":83,
              "y":185},
            "size":{
              "width":21,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d82ad3d5147d46c39fe3ebe1b1aa8e41",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":83,
                  "y":185},
                "size":{
                  "width":21,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u18.png"}},
{
          "id":"2681540037e64acbb433f078085b24fc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":109,
              "y":185},
            "size":{
              "width":21,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e36e8a2060b14ea9a74d5c16acb67dea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":109,
                  "y":185},
                "size":{
                  "width":21,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u18.png"}},
{
          "id":"c0245d46a58443139273bb45a2223d1c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":135,
              "y":185},
            "size":{
              "width":21,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3669ece60eba46efaa79bfe2eb9e77fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":135,
                  "y":185},
                "size":{
                  "width":21,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u18.png"}},
{
          "id":"23d9d9ed3f0545a7ac7ca0d491ab913c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":161,
              "y":185},
            "size":{
              "width":21,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4871dba3a44242acb5338b92e8000906",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":161,
                  "y":185},
                "size":{
                  "width":21,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u18.png"}},
{
          "id":"13a08f1ff354407e907c5fd88bc12e94",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":20,
              "y":230},
            "size":{
              "width":440,
              "height":150},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d94a9fa6537242dabcdbe99dab0c2a07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":20,
                  "y":230},
                "size":{
                  "width":440,
                  "height":150},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u12.png"}},
{
          "id":"0147636688ca44b1829cbdaaf8f68533",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'幼圆 Bold', '幼圆'",
            "location":{
              "x":36,
              "y":245},
            "size":{
              "width":325,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac3d9f262f9f4b67b7a0cfb9a43a1cda",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'幼圆 Bold', '幼圆'",
                "location":{
                  "x":36,
                  "y":245},
                "size":{
                  "width":325,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Hide map fade 500 ms",
                      "objectsToFades":[{
                          "objectPath":["8f5a3886bdeb49a680caf66eec16dfb1"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "easing":"fade",
                              "duration":500,
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"Show map fade 500 ms",
                      "objectsToFades":[{
                          "objectPath":["8f5a3886bdeb49a680caf66eec16dfb1"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"fade",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ecc8fd4f67574fe197aca6f5b0814ab1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":376,
              "y":230},
            "size":{
              "width":84,
              "height":150},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27d52d27823643f48a5495033c92a609",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":376,
                  "y":230},
                "size":{
                  "width":84,
                  "height":150},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Page 2 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"page_2.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/page_1/u16.png"}},
{
          "id":"1a1e5f74e9024e848f11c9778f48ff8d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":83,
              "y":345},
            "size":{
              "width":21,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fee50a6d6c7b477ba3241270d4e2ef58",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":83,
                  "y":345},
                "size":{
                  "width":21,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u18.png"}},
{
          "id":"e03416f8102840fe8a1ea37f916bbc1d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":109,
              "y":345},
            "size":{
              "width":21,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b2de8e4bb8746359a7ddd01c06c8534",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":109,
                  "y":345},
                "size":{
                  "width":21,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u18.png"}},
{
          "id":"328b754ce881443981f794f8a86605d7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":135,
              "y":345},
            "size":{
              "width":21,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f004be32e6cd42a88daae90044c61c56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":135,
                  "y":345},
                "size":{
                  "width":21,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u18.png"}},
{
          "id":"5c5ac8c9806942f28f5e9fab4b2f18e1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":161,
              "y":345},
            "size":{
              "width":21,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca8969e32f3c426092e125f8eba2d329",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":161,
                  "y":345},
                "size":{
                  "width":21,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u18.png"}},
{
          "id":"78ab21d1ace64dbfac66b91935164bd4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":20,
              "y":390},
            "size":{
              "width":440,
              "height":150},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d9327a8c3454ce0b9051bb0446f8d67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":20,
                  "y":390},
                "size":{
                  "width":440,
                  "height":150},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u12.png"}},
{
          "id":"0f92100f191245d88c0436d1c753e1a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'幼圆 Bold', '幼圆'",
            "location":{
              "x":36,
              "y":405},
            "size":{
              "width":325,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82117143f1da4dea8104d38a855e4c81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'幼圆 Bold', '幼圆'",
                "location":{
                  "x":36,
                  "y":405},
                "size":{
                  "width":325,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Hide map fade 500 ms",
                      "objectsToFades":[{
                          "objectPath":["8f5a3886bdeb49a680caf66eec16dfb1"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "easing":"fade",
                              "duration":500,
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"Show map fade 500 ms",
                      "objectsToFades":[{
                          "objectPath":["8f5a3886bdeb49a680caf66eec16dfb1"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"fade",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a58e5157c30547a283687ff53ee9ae2d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":376,
              "y":390},
            "size":{
              "width":84,
              "height":150},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd27f4ab9c904d31ac47ff4e92996527",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":376,
                  "y":390},
                "size":{
                  "width":84,
                  "height":150},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Page 2 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"page_2.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/page_1/u16.png"}},
{
          "id":"1934f46ef49642f5a1b98e32cc719d9c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":83,
              "y":505},
            "size":{
              "width":21,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3f877eca684476bb6913fe78b8f6029",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":83,
                  "y":505},
                "size":{
                  "width":21,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u18.png"}},
{
          "id":"8c1788c6dacf47b4b1ddf8e1f1464a18",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":109,
              "y":505},
            "size":{
              "width":21,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c76feedd7d8489a8aad43e007b7d3ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":109,
                  "y":505},
                "size":{
                  "width":21,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u18.png"}},
{
          "id":"8a114a2b64ac465aa17b9118df7bea36",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":135,
              "y":505},
            "size":{
              "width":21,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d50c5e2d3d64715bee434d2ab04b022",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":135,
                  "y":505},
                "size":{
                  "width":21,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u18.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "d993d1e82c1c4714af9f435e79563a5b":{
      "scriptId":"u0"},
    "2e019c9a074b485b8843927a787cc443":{
      "scriptId":"u1"},
    "03a356bbeb51488eb75550cd59384864":{
      "scriptId":"u2"},
    "8483295623cd489cbc8b8bf410f6dfcb":{
      "scriptId":"u3"},
    "7842372ac2564f7a849166f241575f94":{
      "scriptId":"u4"},
    "adbb2432308b4417b77796b18f3e0f99":{
      "scriptId":"u5"},
    "1c6e5120861b474f89a1b6cc514ff081":{
      "scriptId":"u6"},
    "63e96e3fa5774110a91c24bd3248f842":{
      "scriptId":"u7"},
    "13d728f363f64bab98c01a72e92fa7a9":{
      "scriptId":"u8"},
    "fb0f0429d4a341f8ba97e3af4a3210f4":{
      "scriptId":"u9"},
    "8f5a3886bdeb49a680caf66eec16dfb1":{
      "scriptId":"u10"},
    "14f0d2d4cf7d492c90187a4a0e0a31d1":{
      "scriptId":"u11"},
    "47cd58fcc61e40a199a0dc6056681dac":{
      "scriptId":"u12"},
    "c5374e0ea6444d26941c376235189c80":{
      "scriptId":"u13"},
    "ffc06f03ee6c412682faeaba0c324d0d":{
      "scriptId":"u14"},
    "932df56f7f134a4ea2218a0ac726a0c2":{
      "scriptId":"u15"},
    "66a482416abf4a2ea101d195155d8cac":{
      "scriptId":"u16"},
    "802ff3c182d043a983b33d42a51fea07":{
      "scriptId":"u17"},
    "33c16d887839452f821763f5a8b18203":{
      "scriptId":"u18"},
    "d82ad3d5147d46c39fe3ebe1b1aa8e41":{
      "scriptId":"u19"},
    "2681540037e64acbb433f078085b24fc":{
      "scriptId":"u20"},
    "e36e8a2060b14ea9a74d5c16acb67dea":{
      "scriptId":"u21"},
    "c0245d46a58443139273bb45a2223d1c":{
      "scriptId":"u22"},
    "3669ece60eba46efaa79bfe2eb9e77fe":{
      "scriptId":"u23"},
    "23d9d9ed3f0545a7ac7ca0d491ab913c":{
      "scriptId":"u24"},
    "4871dba3a44242acb5338b92e8000906":{
      "scriptId":"u25"},
    "13a08f1ff354407e907c5fd88bc12e94":{
      "scriptId":"u26"},
    "d94a9fa6537242dabcdbe99dab0c2a07":{
      "scriptId":"u27"},
    "0147636688ca44b1829cbdaaf8f68533":{
      "scriptId":"u28"},
    "ac3d9f262f9f4b67b7a0cfb9a43a1cda":{
      "scriptId":"u29"},
    "ecc8fd4f67574fe197aca6f5b0814ab1":{
      "scriptId":"u30"},
    "27d52d27823643f48a5495033c92a609":{
      "scriptId":"u31"},
    "1a1e5f74e9024e848f11c9778f48ff8d":{
      "scriptId":"u32"},
    "fee50a6d6c7b477ba3241270d4e2ef58":{
      "scriptId":"u33"},
    "e03416f8102840fe8a1ea37f916bbc1d":{
      "scriptId":"u34"},
    "7b2de8e4bb8746359a7ddd01c06c8534":{
      "scriptId":"u35"},
    "328b754ce881443981f794f8a86605d7":{
      "scriptId":"u36"},
    "f004be32e6cd42a88daae90044c61c56":{
      "scriptId":"u37"},
    "5c5ac8c9806942f28f5e9fab4b2f18e1":{
      "scriptId":"u38"},
    "ca8969e32f3c426092e125f8eba2d329":{
      "scriptId":"u39"},
    "78ab21d1ace64dbfac66b91935164bd4":{
      "scriptId":"u40"},
    "0d9327a8c3454ce0b9051bb0446f8d67":{
      "scriptId":"u41"},
    "0f92100f191245d88c0436d1c753e1a1":{
      "scriptId":"u42"},
    "82117143f1da4dea8104d38a855e4c81":{
      "scriptId":"u43"},
    "a58e5157c30547a283687ff53ee9ae2d":{
      "scriptId":"u44"},
    "bd27f4ab9c904d31ac47ff4e92996527":{
      "scriptId":"u45"},
    "1934f46ef49642f5a1b98e32cc719d9c":{
      "scriptId":"u46"},
    "b3f877eca684476bb6913fe78b8f6029":{
      "scriptId":"u47"},
    "8c1788c6dacf47b4b1ddf8e1f1464a18":{
      "scriptId":"u48"},
    "1c76feedd7d8489a8aad43e007b7d3ab":{
      "scriptId":"u49"},
    "8a114a2b64ac465aa17b9118df7bea36":{
      "scriptId":"u50"},
    "1d50c5e2d3d64715bee434d2ab04b022":{
      "scriptId":"u51"}}});